using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using LeaderboardAPI.Models;

namespace LeaderboardAPI.Controllers;

// Marks this class as an API controller, enabling features like automatic HTTP 400 
// error responses if the Unity client sends poorly formatted JSON.
[ApiController]

// Sets the base URL to /api/leaderboard
[Route("api/[controller]")]
public class LeaderboardController : ControllerBase
{
    // A private variable to hold our database connection.
    private readonly LeaderboardContext _context;

    // Dependency Injection: When the server creates this controller to handle a request, 
    // it automatically passes in the active database connection we set up in Program.cs.
    public LeaderboardController(LeaderboardContext context)
    {
        _context = context;
    }

    // ==========================================
    // GET ENDPOINT (Read Data)
    // ==========================================
    
    // Maps to a standard GET request at: /api/leaderboard
    [HttpGet]
    public async Task<IActionResult> GetLeaderboard()
    {
        // Queries the PostgreSQL database. 'await' tells the server to handle other 
        // requests while it waits for the database to finish searching.
        var topScores = await _context.MatchResults
            
            // Sorts the entire MatchResults table from highest score to lowest.
            .OrderByDescending(m => m.Score)
            
            // Grabs only the top 10 rows so we don't send 1,000,000 scores to the game client.
            .Take(10)
            
            // Transforms the raw database rows into a cleaner, anonymous format to send over the network.
            // Notice we are NOT sending the MatchId or database Id, just the data the UI needs.
            .Select(m => new 
            {
                PlayerId = m.PlayerId,
                Score = m.Score,
                Victory = m.DidWin
            })
            
            // Executes the query and packages the results into a C# List.
            .ToListAsync();

        // Returns HTTP 200 OK and automatically serializes the List into a JSON array.
        return Ok(topScores);
    }

    // ==========================================
    // POST ENDPOINT (Write Data)
    // ==========================================
    
    // A Data Transfer Object (DTO) defining exactly what JSON keys to look for.
    public record SubmitScoreRequest(int PlayerId, int MatchId, int Score, bool DidWin);
    
    // Security: This attribute demands that a valid JWT (generated by AuthController) 
    // is included in the HTTP headers. If missing or invalid, it returns 401 Unauthorized.
    [Authorize]
    
    // Maps to a POST request at: /api/leaderboard/scores
    [HttpPost("scores")]
    public async Task<IActionResult> SubmitScore([FromBody] SubmitScoreRequest request)
    {
        // Takes the incoming JSON data (request) and maps it to a new database entity (MatchResult).
        var newScore = new MatchResult
        {
            PlayerId = request.PlayerId,
            MatchId = request.MatchId,
            Score = request.Score,
            DidWin = request.DidWin
        };
        
        // Stages the new score to be inserted into the database. (It is NOT saved yet).
        _context.MatchResults.Add(newScore);
        
        // Actually connects to PostgreSQL and commits the changes. 'await' ensures the 
        // code doesn't continue until the database confirms the row was saved.
        await _context.SaveChangesAsync();
        
        // Returns HTTP 200 OK along with a custom JSON object containing a success message 
        // and the new unique ID the database assigned to this score.
        return Ok(new { Message = "Score saved!", ScoreId = newScore.Id });
    }
}